
preserve_hierarchy: true
project_id: "1"
base_url: https://appliedenergistics2.crowdin.com/api/v2
api_token_env: CROWDIN_TOKEN

files:
  - source: "guidebook/**/*.md"
    translation: "_%two_letters_code%/%original_path%/%original_file_name%"
    ignore:
      - "_%two_letters_code%/**/*"
      - "master/**"
    type: mdx_v2
    translation_replace:
      "_fr/guidebook/": "guidebook/_fr_fr/"
      "_hu/guidebook/": "guidebook/_hu_hu/"
      "_es/guidebook/": "guidebook/_es_es/"
      "_cs/guidebook/": "guidebook/_cs_cz/"
      "_ja/guidebook/": "guidebook/_ja_jp/"
      "_it/guidebook/": "guidebook/_it_it/"
      "_ko/guidebook/": "guidebook/_ko_kr/"
      "_sv/guidebook/": "guidebook/_sv_se/"
      "_pt-BR/guidebook/": "guidebook/_pt_br/"
      "_ro/guidebook/": "guidebook/_ro_ro/"
      "_ru/guidebook/": "guidebook/_ru_ru/"
      "_de/guidebook/": "guidebook/_de_de/"
      "_tr/guidebook/": "guidebook/_tr_tr/"
      "_uk/guidebook/": "guidebook/_uk_ua/"
      "_zh-CN/guidebook/": "guidebook/_zh_cn/"
      "_zh-TW/guidebook/": "guidebook/_zh_tw/"
