name: 'Checkout'
description: 'Properly check out (with tags)'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      if: !startsWith(github.ref, 'refs/tags/')
      with:
        fetch-depth: 100
        fetch-tags: true
    # The action is buggy when building a tag
    - run: git fetch origin --tags
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
