package appeng.client.gui;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.Set;

import org.junit.jupiter.api.Test;

/**
 * test lines are based on MathExpressionParserTest
 * with more than 1500+ different causes, it will cover more than 99% situations
 * @author HowXu <dev@howxu.cn>
 */
public class MathExpressionParserCoverTest {

    /**
     * Note: these examples lines generated by agents 
     * cause it's too many and if I judge them by myself it will cause whole 3 days T_T
     */
    @Test
    void suffixCoverageForOnePlusTwo() {
        assertInsertions("1 + 2", valid(1, 5), invalid(2, 3, 4));
    }

    @Test
    void suffixCoverageForThreeTimesFourWithTrailingSpace() {
        assertInsertions("3 *4 ", valid(1, 4), invalid(2, 3, 5));
    }

    @Test
    void suffixCoverageForOnePlusTwoTimesThree() {
        assertInsertions("1 + 2 * 3", valid(1, 5, 9), invalid(2, 3, 4, 6, 7, 8));
    }

    @Test
    void suffixCoverageForOneMinusSix() {
        assertInsertions("1 - 6", valid(1, 5), invalid(2, 3, 4));
    }

    @Test
    void suffixCoverageForOneDividedByThree() {
        assertInsertions("1/3", valid(1, 3), invalid(2));
    }

    @Test
    void suffixCoverageForDecimalAddition() {
        assertInsertions("23.4 + 0.6", valid(4, 10), invalid(1, 2, 3, 5, 6, 7, 8, 9));
    }

    @Test
    void suffixCoverageForMinusNegativeFour() {
        assertInsertions("1 - -4", valid(1, 6), invalid(2, 3, 4, 5));
    }

    @Test
    void suffixCoverageForChainedMultiplication() {
        assertInsertions("1 + 4*3*2", valid(1, 5, 7, 9), invalid(2, 3, 4, 6, 8));
    }

    @Test
    void suffixCoverageForDivisionByZero() {
        assertInsertions("1/0", valid(1, 3), invalid(2));
    }

    @Test
    void suffixCoverageForParenthesizedDivisionByZero() {
        assertInsertions("1/(1 - 1)", valid(1, 4, 8, 9), invalid(2, 3, 5, 6, 7));
    }

    @Test
    void suffixCoverageForMixedOperators() {
        assertInsertions("3 + 2 * 4 - 1 /2", valid(1, 5, 9, 13, 16),
                invalid(2, 3, 4, 6, 7, 8, 10, 11, 12, 14, 15));
    }

    @Test
    void suffixCoverageForNestedParentheses() {
        assertInsertions("1 + (2 * (2 * (1 + 1)))", valid(1, 6, 11, 16, 20, 21, 22, 23),
                invalid(2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 15, 17, 18, 19));
    }

    @Test
    void suffixCoverageForInvalidLetters() {
        assertInsertions("arkazkdhz", valid(), invalid(1, 2, 3, 4, 5, 6, 7, 8, 9));
    }

    @Test
    void suffixCoverageForAdjacentNumbers() {
        assertInsertions("1 + 2 3 7 - 1", valid(1, 5, 7, 9, 13),
                invalid(2, 3, 4, 6, 8, 10, 11, 12));
    }

    @Test
    void suffixCoverageForRepeatedBinaryOperator() {
        assertInsertions("2 + + 2", valid(1, 7), invalid(2, 3, 4, 5, 6));
    }

    @Test
    void suffixCoverageForScientificNotationLikeInput() {
        assertInsertions("10e6", valid(), invalid(1, 2, 3, 4));
    }

    @Test
    void suffixCoverageForNegativeOneMinusOne() {
        assertInsertions("-1 -1", valid(2, 5), invalid(1, 3, 4));
    }

    @Test
    void suffixCoverageForUnaryMinusBeforeParentheses() {
        assertInsertions("- (1 + 1)", valid(4, 8, 9), invalid(1, 2, 3, 5, 6, 7));
    }

    @Test
    void suffixCoverageForMultiplicationByNegativeOne() {
        assertInsertions("2 * -1", valid(1, 6), invalid(2, 3, 4, 5));
    }

    @Test
    void suffixCoverageForTwoMinusTwoWithoutWhitespace() {
        assertInsertions("2 -2", valid(1, 4), invalid(2, 3));
    }

    @Test
    void suffixCoverageForUnaryMinusWithWhitespace() {
        assertInsertions("-  1", valid(4), invalid(1, 2, 3));
    }

    @Test
    void suffixCoverageForNegativeOne() {
        assertInsertions("-1", valid(2), invalid(1));
    }

    @Test
    void suffixCoverageForRepeatedUnaryMinus() {
        assertInsertions("- - - - - 5", valid(11), invalid(1, 2, 3, 4, 5, 6, 7, 8, 9, 10));
    }

    @Test
    void suffixCoverageForNestedUnaryMinusParentheses() {
        assertInsertions("-(-(-(-2)))", valid(8, 9, 10, 11), invalid(1, 2, 3, 4, 5, 6, 7));
    }

    @Test
    void suffixCoverageForOneMinusNegativeOne() {
        assertInsertions("1 - -1", valid(1, 6), invalid(2, 3, 4, 5));
    }

    @Test
    void suffixCoverageForUnclosedParentheses() {
        assertInsertions("1 + -(2", valid(1, 7), invalid(2, 3, 4, 5, 6));
    }

    @Test
    void suffixCoverageForNaN() {
        assertInsertions("NaN", valid(), invalid(1, 2, 3));
    }

    @Test
    void suffixCoverageForSpacedDivisionByZero() {
        assertInsertions("1 / 0", valid(1, 5), invalid(2, 3, 4));
    }

    @Test
    void suffixCoverageForSixtyFourDividedByFour() {
        assertInsertions("64/4", valid(2, 4), invalid(1, 3));
    }

    @Test
    void suffixCoverageForNegativeTwoSquared() {
        assertInsertions("-2^2", valid(2, 4), invalid(1, 3));
    }

    @Test
    void suffixCoverageForTwoSquaredTimesThree() {
        assertInsertions("2^2*3", valid(1, 3, 5), invalid(2, 4));
    }

    @Test
    void suffixCoverageForDecimalExponent() {
        assertInsertions("2^3.1", valid(1, 5), invalid(2, 3, 4));
    }

    @Test
    void suffixCoverageForExponentTooLarge() {
        assertInsertions("2^31", valid(1, 4), invalid(2, 3));
    }

    @Test
    void suffixCoverageForChainedExponentiation() {
        assertInsertions("2^3^4", valid(1, 3, 5), invalid(2, 4));
    }

    @Test
    void suffixCoverageForRepeatedHugeExponentiation() {
        assertInsertions("2^30^30^30", valid(1, 4, 7, 10), invalid(2, 3, 5, 6, 8, 9));
    }

    @Test
    void suffixCoverageForNegativeExponent() {
        assertInsertions("2^-1", valid(1, 4), invalid(2, 3));
    }

    @Test
    void suffixesDoNotWorkAsPrefixesOrStandaloneTokens() {
        for (var suffix : suffixes()) {
            assertFails(suffix.text() + "(1+2)");
            assertFails(suffix.text() + "1");
            assertFails("-" + suffix.text());
            assertFails("1 + " + suffix.text() + "2");
            assertFails("1 " + suffix.text() + "+2");
            assertFails("1" + suffix.text() + "10");
            assertFails("1" + suffix.text() + "(10)");
            assertFails("1" + suffix.text() + suffix.text());
        }
    }

    @Test
    void bareSuffixesAreInvalid() {
        for (var suffix : suffixes()) {
            assertFails(suffix.text());
            assertFails("+" + suffix.text());
            assertFails("-" + suffix.text());
            assertFails("(" + suffix.text() + ")");
            assertFails("1+" + suffix.text());
            assertFails("1-" + suffix.text());
            assertFails("1*" + suffix.text());
            assertFails("1/" + suffix.text());
            assertFails("1^" + suffix.text());
        }
    }

    @Test
    void suffixesMustBeImmediatelyAfterANumberOrClosingParenthesis() {
        for (var suffix : suffixes()) {
            assertFails("1 " + suffix.text());
            assertFails("1 " + suffix.text() + "+2");
            assertFails("1\t" + suffix.text());
            assertFails("(1+2) " + suffix.text());
            assertFails("(1+2) " + suffix.text() + "+3");
            assertFails("1+ " + suffix.text() + "2");
            assertFails("(" + suffix.text() + "1+2)");
            assertFails("(1+" + suffix.text() + "2)");
        }
    }

    @Test
    void suffixesRejectTrailingTokensThatWouldImplyImplicitMultiplicationOrAnotherNumber() {
        for (var suffix : suffixes()) {
            assertFails("1" + suffix.text() + "2");
            assertFails("1" + suffix.text() + ".2");
            assertFails("1" + suffix.text() + "(2)");
            assertFails("1" + suffix.text() + "K");
            assertFails("1" + suffix.text() + "ki");
            assertFails("(1+2)" + suffix.text() + "3");
            assertFails("(1+2)" + suffix.text() + "(3)");
            assertFails("(1+2)" + suffix.text() + suffix.text());
        }
    }

    @Test
    void unsupportedBinarySuffixFragmentsAreInvalid() {
        assertFails("i");
        assertFails("I");
        assertFails("1i");
        assertFails("1I");
        assertFails("1ik");
        assertFails("1iK");
        assertFails("1Ik");
        assertFails("1IK");
        assertFails("1kii");
        assertFails("1kiI");
        assertFails("1kii+2");
        assertFails("1k i");
        assertFails("1ki i");
    }

    @Test
    void malformedParenthesizedSuffixExpressionsAreInvalid() {
        for (var suffix : suffixes()) {
            assertFails("()" + suffix.text());
            assertFails("( )" + suffix.text());
            assertFails("(1+)" + suffix.text());
            assertFails("(+1)" + suffix.text());
            assertFails("(1 2)" + suffix.text());
            assertFails("(1+2" + suffix.text());
            assertFails("((1+2)" + suffix.text());
            assertFails("(1+2))" + suffix.text());
        }
    }

    @Test
    void suffixesParseToExpectedDecimalAndBinaryValues() {
        assertParsesAs("1k", "1000");
        assertParsesAs("1K", "1000");
        assertParsesAs("1m", "1000000");
        assertParsesAs("1M", "1000000");
        assertParsesAs("1g", "1000000000");
        assertParsesAs("1G", "1000000000");
        assertParsesAs("1t", "1000000000000");
        assertParsesAs("1T", "1000000000000");

        assertParsesAs("1ki", "1024");
        assertParsesAs("1kI", "1024");
        assertParsesAs("1Ki", "1024");
        assertParsesAs("1KI", "1024");
        assertParsesAs("1mi", "1048576");
        assertParsesAs("1Mi", "1048576");
        assertParsesAs("1gi", "1073741824");
        assertParsesAs("1Gi", "1073741824");
        assertParsesAs("1ti", "1099511627776");
        assertParsesAs("1Ti", "1099511627776");
    }

    @Test
    void suffixesParseCorrectlyInsideExpressions() {
        assertParsesAs("1k+2", "1002");
        assertFails("1+k2");
        assertParsesAs("1+2k", "2001");
        assertParsesAs("1ki+2", "1026");
        assertParsesAs("1+2ki", "2049");
        assertParsesAs("1.5k", "1500");
        assertParsesAs("1.5ki", "1536.0");
        assertParsesAs("(1+2)k", "3000");
        assertParsesAs("(1+2)ki", "3072");
        assertParsesAs("2*(1+2)k", "6000");
        assertParsesAs("(1+2)k/3", "1000.00000000");
    }

    @Test
    void zeroSuffixValuesParseAsZeroInTheParser() {
        assertParsesAs("0k", "0");
        assertParsesAs("0ki", "0");
        assertParsesAs("0K", "0");
        assertParsesAs("0KI", "0");
        assertParsesAs("0k+1", "1");
        assertParsesAs("(0)ki", "0");
    }

    private static void assertInsertions(String expression, int[] validOffsets, int[] invalidOffsets) {
        assertOffsetsCoverExpression(expression, validOffsets, invalidOffsets);

        for (int offset : validOffsets) {
            for (var suffix : suffixes()) {
                var expressionWithSuffix = insert(expression, offset, suffix.text());
                var expectedExpression = multiplyPreviousOperand(expression, offset, suffix.multiplier());
                var expected = parse(expectedExpression);
                var actual = parse(expressionWithSuffix);

                if (expected.isPresent()) {
                    assertTrue(actual.isPresent(), () -> expressionWithSuffix + " should parse as " + expected.get()
                            + " via " + expectedExpression);
                    assertEquals(0, actual.get().compareTo(expected.get()),
                            () -> expressionWithSuffix + " should parse as " + expected.get() + " via "
                                    + expectedExpression + ", but got " + actual.get());
                } else {
                    assertTrue(actual.isEmpty(), () -> expressionWithSuffix + " should fail like " + expectedExpression
                            + ", but got " + actual.get());
                }
            }
        }

        for (int offset : invalidOffsets) {
            for (var suffix : suffixes()) {
                assertFails(insert(expression, offset, suffix.text()));
            }
        }
    }

    private static void assertOffsetsCoverExpression(String expression, int[] validOffsets, int[] invalidOffsets) {
        Set<Integer> seen = new HashSet<>();
        for (int offset : validOffsets) {
            assertTrue(offset > 0 && offset <= expression.length(), () -> "Invalid valid offset " + offset);
            assertTrue(seen.add(offset), () -> "Duplicate offset " + offset + " for " + expression);
        }
        for (int offset : invalidOffsets) {
            assertTrue(offset > 0 && offset <= expression.length(), () -> "Invalid invalid offset " + offset);
            assertTrue(seen.add(offset), () -> "Duplicate offset " + offset + " for " + expression);
        }
        assertEquals(expression.length(), seen.size(), () -> "Missing insertion offset for " + expression);
    }

    private static void assertFails(String expression) {
        var parsed = parse(expression);
        assertTrue(parsed.isEmpty(), () -> expression + " should fail, but got " + parsed.get());
    }

    private static void assertParsesAs(String expression, String expected) {
        var parsed = parse(expression);
        assertTrue(parsed.isPresent(), () -> expression + " should parse as " + expected);
        assertEquals(0, parsed.get().compareTo(new BigDecimal(expected)),
                () -> expression + " should parse as " + expected + ", but got " + parsed.get());
    }

    private static String multiplyPreviousOperand(String expression, int offset, BigDecimal multiplier) {
        int operandStart = findOperandStart(expression, offset);
        return expression.substring(0, operandStart)
                + "("
                + expression.substring(operandStart, offset)
                + "*"
                + multiplier.toPlainString()
                + ")"
                + expression.substring(offset);
    }

    private static int findOperandStart(String expression, int offset) {
        int lastChar = offset - 1;
        if (expression.charAt(lastChar) != ')') {
            int start = lastChar;
            while (start > 0) {
                char previous = expression.charAt(start - 1);
                if (!Character.isDigit(previous) && previous != '.') {
                    break;
                }
                start--;
            }
            return start;
        }

        int depth = 0;
        for (int i = lastChar; i >= 0; i--) {
            char c = expression.charAt(i);
            if (c == ')') {
                depth++;
            } else if (c == '(') {
                depth--;
                if (depth == 0) {
                    return i;
                }
            }
        }
        throw new IllegalArgumentException("Could not find matching '(' in " + expression + " at " + offset);
    }

    private static Optional<BigDecimal> parse(String expression) {
        return MathExpressionParser.parse(expression, createFormat());
    }

    private static String insert(String expression, int offset, String suffix) {
        return expression.substring(0, offset) + suffix + expression.substring(offset);
    }

    private static int[] valid(int... offsets) {
        return offsets;
    }

    private static int[] invalid(int... offsets) {
        return offsets;
    }

    private static List<Suffix> suffixes() {
        var suffixes = new ArrayList<Suffix>();

        addDecimalSuffixes(suffixes, 'k', 1_000L);
        addDecimalSuffixes(suffixes, 'm', 1_000_000L);
        addDecimalSuffixes(suffixes, 'g', 1_000_000_000L);
        addDecimalSuffixes(suffixes, 't', 1_000_000_000_000L);

        addBinarySuffixes(suffixes, 'k', 1L << 10);
        addBinarySuffixes(suffixes, 'm', 1L << 20);
        addBinarySuffixes(suffixes, 'g', 1L << 30);
        addBinarySuffixes(suffixes, 't', 1L << 40);

        return suffixes;
    }

    private static void addDecimalSuffixes(List<Suffix> suffixes, char prefix, long multiplier) {
        suffixes.add(new Suffix(String.valueOf(prefix), BigDecimal.valueOf(multiplier)));
        suffixes.add(new Suffix(String.valueOf(Character.toUpperCase(prefix)), BigDecimal.valueOf(multiplier)));
    }

    private static void addBinarySuffixes(List<Suffix> suffixes, char prefix, long multiplier) {
        for (var prefixCase : List.of(prefix, Character.toUpperCase(prefix))) {
            for (var iCase : List.of('i', 'I')) {
                suffixes.add(new Suffix("" + prefixCase + iCase, BigDecimal.valueOf(multiplier)));
            }
        }
    }

    // Note: based on MathExpressionParserTest.testThird
    private static DecimalFormat createFormat() {
        var format = new DecimalFormat("#.######", DecimalFormatSymbols.getInstance(Locale.US));
        format.setParseBigDecimal(true);
        format.setNegativePrefix("-");
        return format;
    }

    private record Suffix(String text, BigDecimal multiplier) {
    }
}
