blank_issues_enabled: true
contact_links:
  - name: AE2 Discord Server
    url: https://discord.gg/Zd6t9ka7ne
    about: Please use our Discord for questions or help. Issues should be used for bug reports, feature requests or similar.