name: 'Gradle Setup'
description: 'Set up the basics to run gradle'
runs:
  using: "composite"
  steps:
    - name: Export release tag as environment variable
      env:
        TAG: ${{ github.event.release.tag_name }}
      run: |
        echo "TAG=${TAG}" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
