modLoader="javafml"
loaderVersion="[1,)"
logoFile="logo.png"
license="See GitHub repository for details"
issueTrackerURL="https://github.com/AppliedEnergistics/Applied-Energistics-2/issues"

[[mods]]
modId="ae2"
version="${version}"
displayName="Applied Energistics 2"
description="A Mod about Matter, Energy and using them to conquer the world..."
authors="Team AppliedEnergistics"
displayURL="https://appliedenergistics.org"

[[mixins]]
config="ae2.mixins.json"

[[dependencies.ae2]]
    modId="neoforge"
    type="REQUIRED"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.ae2]]
    modId="minecraft"
    type="REQUIRED"
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.ae2]]
    modId="guideme"
    type="REQUIRED"
    versionRange="[${guideme_version},)"
    side="BOTH"

[[dependencies.ae2]]
    modId="emi"
    type="OPTIONAL"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ae2]]
    modId="theoneprobe"
    type="OPTIONAL"
    versionRange="${top_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ae2]]
    modId="jade"
    type="OPTIONAL"
    versionRange="${jade_version_range}"
    ordering="AFTER"
    side="BOTH"


# VanillaFix caused us grief in the past
# https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8034
# https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7539
[[dependencies.ae2]]
    modId="vanillafix"
    type="discouraged"
    reason="VanillaFix breaks some NeoForge features that AE2 depends on. Do not report AE2 bugs if VanillaFix is present."
