name: 'Gradle Setup'
description: 'Set up the basics to run gradle'
runs:
  using: "composite"
  steps:
    - name: Export release tag as environment variable
      shell: bash
      env:
        TAG: ${{ github.event.release.tag_name }}
      run: |
        echo "TAG=${TAG}" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
