name: 'Site Export'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install xvfb mesa-utils pngcrush
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Use gradle cache for faster builds
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Clean gradle
        run: ./gradlew clean --no-daemon
      - name: Validate no assets
        run: test ! -d ./src/generated
      - name: Generate assets
        run: ./gradlew runData --no-daemon
      - name: Validate assets
        run: test -d ./src/generated -a -f ./src/generated/resources/.cache/cache
      - name: Build with Gradle
        run: |
          export LIBGL_ALWAYS_SOFTWARE=true
          xvfb-run glxinfo
          xvfb-run --auto-servernum ./gradlew runSiteExport --no-daemon --info
      - name: Optimize PNG
        run: |
          find build/site-export -name "*.png" -exec pngcrush -ow {} \;
      - name: Upload Site Export
        uses: actions/upload-artifact@v2
        with:
          name: site-export
          path: |
            build/site-export
